- type: latheRecipe
  id: ADTMagazineMagnumEmpty
  result: MagazineMagnumEmpty
  completetime: 5
  materials:
    Steel: 25

- type: latheRecipe
  id: ADTMagazineMagnum
  result: MagazineMagnum
  completetime: 5
  materials:
    Steel: 170

- type: latheRecipe
  id: ADTMagazineMagnumIncendiary
  result: ADTMagazineMagnumIncendiary
  completetime: 5
  materials:
    Steel: 25
    Plastic: 145

- type: latheRecipe
  id: ADTMagazineMagnumUranium
  result: MagazineMagnumUranium
  completetime: 5
  materials:
    Steel: 25
    Plastic: 145
    Uranium: 125

